### PR TITLE
Added GELF logger

### PR DESCRIPTION
**Pull request by benoist**

### CODE REVIEW

**Comment by benoist** [comment]
Not sure if this should be under Logging or Third party API's, what do you think?

**Comment by veelenga** [comment]
Logging is ok, but you forget to add that section to table of contents...

**Comment by benoist** [comment]
Whoops, it's added :)

**Comment by veelenga** [comment]
Tests fail because it broke alphabetical order. Should be:

* Logging and monitoring
* Low level bindings

Please also change order of the section itself, not just order in table of contents.

**Comment by benoist** [comment]
Fixed and squashed

**Comment by veelenga** [comment]
Awesome. Thank you!

**Pull request merged**
