### PR TITLE
Add scry and mint

### PR DESCRIPTION
**Pull request by faustinoaq**
Hi @veelenga 

This PR adds 2 new shads:

1. Scry - LSP for crystal https://github.com/crystal-lang-tools/scry
2. ~~Mint - A refreshing programming language for the font-end web. https://www.mint-lang.com~~

### CODE REVIEW

**Comment by veelenga** [comment]
Unfortunately, mint is too young for this list.

https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md

**Comment by RX14** [comment]
@veelenga it's 20k lines of code, I think exceptions can be made.

cc @gdotdesign

**Comment by gdotdesign** [comment]
@veelenga I agree. I'll create a PR for it when I'm done with the first public release in a couple of weeks.

**Comment by RX14** [comment]
@gdotdesign thanks for the input. I really love mint, i'll be really looking forward to it's first release and inclusion on this list. I like your decision not to shout that it's written in crystal :)

**Comment by faustinoaq** [comment]
@gdotdesign @veelenga Done! :+1:

**Comment by faustinoaq** [comment]
> I like your decision not to shout that it's written in crystal on the front page of the website :)

Yeah, that's nice :wink:

**Comment by RX14** [comment]
People discovering what language it's implemented in naturally is going to leave a bigger impact than implying that it's a feature.

**Comment by veelenga** [comment]
@gdotdesign looking forward to it. Thank you.

**Pull request merged**
