### PR TITLE
Add tourmaline Telegram Bot API wrapper

### PR DESCRIPTION
**Pull request by watzon**

### CODE REVIEW

**Comment by veelenga** [comment]
We can't merge it, at least because of a merge conflict :)

There are also 2 Telegram Bot API wrappers already on the list. How is the new library different?

**Comment by watzon** [comment]
My library is directly based off of the top Ruby gem for the telegram bot API with some additional inspiration taken from the Telegraf and TgBot frameworks. Unlike the other frameworks it is being maintained, it allows the use of middleware, it has the ability to listen to all included events (and some special ones), and more. I have also included usage examples such as how to integrate it with ngrok.cr for easier development with websockets.

**Comment by vladfaust** [comment]
FYI, Tele *is* being maintained; it just has no immediate features requests ATM. I don't mind having more libraries, it's always good to have a wider choice!

**Comment by watzon** [comment]
I also rebased this, so it should be good to merge

**Comment by veelenga** [comment]
@watzon Okay. What about specs, source code formatting, first Travis build?

**Comment by watzon** [comment]
I don't have specs and they're not coming anytime soon. To get any kind of real meaningful specs I need a few more features to be added to webmock.cr. I just ran `crystal tool format` though and fixed the formatting.

**Pull request merged**
