### PR TITLE
Add crystal-money/money shard

### PR DESCRIPTION
**Pull request by Sija**
Adds [money](https://github.com/crystal-money/money) shard.

### CODE REVIEW

**Comment by veelenga** [comment]
If there is an easy way to fix the spec, please go ahead. If not, just remove the url from the description.

**Comment by veelenga** [comment]
What the difference between your shard and moola?

**Comment by veelenga** [comment]
What’s the difference between one and moola?

**Comment by Sija** [comment]
@veelenga Fixed. Regarding your question, money shard is more comprehensive (look at sheer SLOC no).

**Pull request merged**
