### PR TITLE
Add IU - UI framework based on the Fusion/libui.cr library

### PR DESCRIPTION
**Pull request by grkek**
## Link
https://github.com/grkek/iu

## Checklist
* [x] - Shard is at least 30 days old.
* [x] - Shard has CI implemented.
* [x] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).

I don't think an UI framework needs a CI to keep it in check?

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
> I don't think an UI framework needs a CI to keep it in check?

IMO CI is still useful even if it's just ensuring an example still compiles.

**Comment by grkek** [comment]
> > I don't think an UI framework needs a CI to keep it in check?
> 
> IMO CI is still useful even if it's just ensuring an example still compiles.

Not cool mate, how do you expect me to CI test a GUI framework? 

By taking screenshots if the element sits right?

**Comment by Blacksmoke16** [comment]
> how do you expect me to CI test a GUI framework?

Install the required libs, run an example, and assert it exits with code `0` would probably be fine.

> By taking screenshots if the element sits right?

No.  All I'm suggesting is to make sure the framework _compiles_, not if it produces correct UI output.

**Comment by grkek** [comment]
> > how do you expect me to CI test a GUI framework?
> 
> Install the required libs, run an example, and assert it exits with code `0` would probably be fine.
> 
> > By taking screenshots if the element sits right?
> 
> No. All I'm suggesting is to make sure the framework _compiles_, not if it produces correct UI output.

I cant do that since LibUI requires additional installation agents and a big clusterfuck handling of the libui libraries which cant be implemented by a CI tbh

**Comment by Blacksmoke16** [comment]
And there's not _any_ form of tests you can write to ensure things are working as expected?

**Comment by grkek** [comment]
> And there's not _any_ form of tests you can write to ensure things are working as expected?

No I cant because LibUI requires additional components to function, everything is tied to LibUI and it doesnt make any sense to do so.

**Comment by hugoabonizio** [comment]
Well, maybe you can take inspiration from those examples:

- https://github.com/beriberikix/libui-rs/blob/master/.travis.yml
- https://github.com/mischnic/libui-napi/blob/master/.travis.yml

**Pull request merged**
