### PR TITLE
adding clear to the list

### PR DESCRIPTION
**Pull request by anykeyh**
Hello !

I'm adding here the shard I'm working on, because it starts to be stable enough to play with, and I need review for going further into it.

It's an ORM for PostgreSQL, and it already offers lots of features some of the ORM here are not  covering (e.g. cursored each, foreign key constraints, save-point, n+1 and n...(n+1) queries caching)

Note than there's no release yet, as I'm still working hard to cover everything with specs.

### CODE REVIEW

**Comment by tbrand** [comment]
It seems quite good library, but I think you should release first version of it.

**Comment by anykeyh** [comment]
Yes, it's not yet done, still in progress, but already usable. Actually I'm looking for heroes willing to use it and spam me with issues opening to improve it 🤣 

I'm going to release a version next week-end, if I have time to fix the specs and cover most of the shard. Let's keep this PR open until I deploy it !

**Comment by tbrand** [comment]
> Actually I'm looking for heroes willing to use it and spam me with issues opening to improve it

That's the reason why you should release although the library is not stable.

> Let's keep this PR open until I deploy it !

Ok :)

**Comment by RX14** [comment]
Looks like a really good library, if a bit macro-heavy. I think that the amaount of macros could be reduced with some creativity by extracting some more logic into private methods.

Another nitpick: `{a, b}.join` has better performance than `[a, b].join`. I'm not sure why you use named tuples instead of named arguments (`where({published: true})` instead of `where(published: true)`). You can use `rand(4..8)` instead of `(4..8).to_a.sample` and it has better performance.

**Comment by RX14** [comment]
Regarding macros, you should always start without macros. Build the absolute best and most high-level interface you can think of without using any macros at all, *then* introduce macros to take care of the remaining boilerplate.

But that's just me complaining about code quality. What really matters is that it works, which this seems to do, and do well.

**Comment by vladfaust** [comment]
@RX14, does speed difference between ‘rand(4..8)’ and ‘(4..8).to_a.sample’ costs readability impact? Crystal is very fast itself + ORM operations never about millions iterations in a row... Just shower thoughts 💭

**Comment by anykeyh** [comment]
Well, I must say your comments make me feel good 👍, with a new energy to keep my goal which is "modest": having the best PostgreSQL ORM possible, making use of all the powerful functionnalities of this great DBMS I felt in love with long time ago 😅.

Also, I must agree with @RX14, the macro system makes things hard to read. The relation system, with caching of N+1 requests is a good example of big headaches I had. But for now my goal is to keep pace with specs & features, keep code architecture clean if possible. Usage of tuple is a good idea, I use Array since... well since I'm Rubyist first  
And seriously, I'm quite proud of the SQL builder + Expression engine, quite clean in comparison to `arel` for those who were curious enough to give a look 🤣 

I guess for the first release I'll focus on spec writing, ensuring all the basic model lifecycle (`save`, `validate` etc...) is covered and is working. Thus, this shard would be sub-production grade. And finalize the CLI, at least having migration tools + a basic project scaffolding generator using kemal on frontend. We always underestimate end-user experience.

My second goal is to use crystal asap in a production-grade project for my company, probably with Kemal, [GraphQL Crystal](https://github.com/ziprandom/graphql-crystal) and this ORM.

**Comment by RX14** [comment]
@vladfaust `rand(4..8)` is both more understandable, shorter, and faster. What do you mean?

**Comment by vladfaust** [comment]
@RX14 I'm sorry. I first read "change rand to sample". I agree with you then.

**Comment by anykeyh** [comment]
Hello !

I've updated the shards and released it in a `v0.1-alpha` version (meaning: dangerously unstable 😉 ) 🍾 ⭐️ 🥇

**Comment by veelenga** [comment]
Awesome! Thank you

**Pull request merged**
