### PR TITLE
Round two of erroneous shard removal

### PR DESCRIPTION
**Pull request by Blacksmoke16**
* Continues #453 by removing shards that have CI, but has never been ran.
  * Adds some additional shards to the exempt list, if there are anymore that should be there let me know
    * Not sure if they're all still maintained tho :man_shrugging:
  * Fixes owner of cadmium \cc @watzon 

Let me know in the comments if you setup period CI builds and I can update the list/add the shard back.

### Removed Shards

https://github.com/Angarsk8/realtime-todo-app - @Angarsk8
https://github.com/ChangJoo-Park/kemal-vue-chat - @ChangJoo-Park
https://github.com/DougEverly/slack.cr - @DougEverly
https://github.com/Fusion/libui.cr - @Fusion
https://github.com/Papierkorb/qt5.cr - @Papierkorb
https://github.com/Qwerp-Derp/hedron - @Qwerp-Derp
~https://github.com/RX14/predict.cr - @RX14~
https://github.com/TechMagister/bindgencr - @TechMagister
https://gitlab.com/Zatherz/cray - @Zatherz
https://github.com/aisrael/migro - @aisrael
https://github.com/akwiatkowski/kemal-auth-token - @akwiatkowski
https://github.com/andrewsuzuki/termbox-crystal - @andrewsuzuki
https://github.com/anykeyh/crystal-coverage - @anykeyh
https://github.com/arcage/crystal-logreader - @arcage
~https://github.com/arcage/crystal-email - @arcage~
https://github.com/askn/crystal-by-example - @askn
https://github.com/bararchy/mos_game - @bararchy
https://github.com/barisbalic/crystal-monzo - @barisbalic
https://github.com/bitfex/capistrano-kemal - @bitfex
https://github.com/blocknotes/manual-generator - @blocknotes
https://github.com/cagataycali/kemal-heroku-example - @cagataycali
https://github.com/codenoid/crystal-mysql-crud-example - @codenoid
https://github.com/codenoid/jihantoro-cr-mysql - @codenoid
https://github.com/codenoid/jihantoro.sd - @codenoid
https://github.com/codenoid/kemal-mysql-blog - @codenoid
https://github.com/codenoid/chuck-norris-holy-quotes - @codenoid
https://github.com/colstrom/zq - @colstrom
https://github.com/drujensen/delimiter_tree - @drujensen
https://github.com/elorest/compiled_license - @elorest
https://github.com/elorest/bitfields - @elorest
https://github.com/elorest/crelease - @elorest
https://github.com/f/completion - @f
https://github.com/f/kemal-react-chat - @f
https://github.com/f/temel - @f
https://github.com/f/guardian - @f
https://github.com/gdotdesign/cr-melon - @gdotdesign
https://github.com/instana/crystal-sensor - @instana
https://github.com/jasonl99/lattice-core - @jasonl99
https://github.com/jasonl99/card_game - @jasonl99
https://github.com/kemalcr/spec-kemal - @kemalcr
https://github.com/kostya/cron_scheduler - @kostya
https://github.com/kostya/crystal-benchmarks-game - @kostya
https://github.com/kuende/murmur3 - @kuende
https://github.com/l3kn/raytracer - @l3kn
https://github.com/naqvis/brotli.cr - @naqvis
https://github.com/naqvis/xz.cr - @naqvis
https://github.com/oprypin/crsfml-examples - @oprypin
https://github.com/osfx/open_exchange_rates - @osfx
https://github.com/papilip/helptransl8 - @papilip
https://github.com/phoffer/crystalized_ruby - @phoffer
https://github.com/puppetpies/kemal-monetdb - @puppetpies
https://github.com/puppetpies/crystal-monetdb-libmapi - @puppetpies
https://github.com/romeroadrian/nes.cr - @romeroadrian
https://github.com/samueleaton/sentry - @samueleaton
https://github.com/samueleaton/cache-hash - @samueleaton
https://github.com/sdogruyol/kemal-chat - @sdogruyol
https://github.com/sdogruyol/fast-http-server - @sdogruyol
https://github.com/spalger/crystal-mime - @spalger
https://github.com/stumpycr/stumpy_gif - @stumpycr
https://github.com/timcraft/nexmo-crystal - @timcraft
https://github.com/vonKingsley/crass - @vonKingsley
https://github.com/waterlink/query.cr - @waterlink
https://github.com/ysbaddaden/prax.cr - @ysbaddaden
https://github.com/ysbaddaden/posix - @ysbaddaden

### CODE REVIEW

**Comment by zatherz** [comment]
Got pinged because of a binding I wrote like 2 years ago and I don't really understand. Is this just pointless jerking off over CI setups for sub-1k line libraries that barely anybody uses?

**Comment by Blacksmoke16** [comment]
The point of this is to ensure that the shards in the repo still compile and work as intended.  CI ensures that both of those are still true.

#347 Made it a requirement that shards have period CI builds.  This PR is a part of the process to cleanup the shards that do not.

This isn't anything personal to anyone in particular.  If you're not maintaining your shards anymore just hit the `Unsubscribe` button and don't worry about it.

Otherwise, I mention people to give them time to update their shard to have CI, even if it's like a single simple test to ensure it still compiles.  

It's not a good experience when you have a repo of like "come checkout all the cool Crystal shards we have" when over half of them don't even work anymore.

**Comment by Blacksmoke16** [comment]
@veelenga I'm recalculating the list now, just in case anyone added it since I originally opened this PR. 

> @Blacksmoke16 can you confirm this is the final step of the cleanup?

No, there is one more batch of repos that CI hasn't been built in more than 30 days; which would be those without periodic builds.

**Comment by elorest** [comment]
The following 3 libraries are maintained and currently used in quite a few other projects. Sorry I've been traveling a lot for work lately. What needs to be done with these? They all of passing specs.

https://github.com/elorest/compiled_license - @elorest
https://github.com/elorest/bitfields - @elorest
https://github.com/elorest/crelease - @elorest

**Comment by Blacksmoke16** [comment]
@elorest Could you set up some form of CI for them with period builds?  I.e. Travis, Github Actions, Circle etc.

**Comment by elorest** [comment]
> @elorest Could you set up some form of CI for them with period builds? I.e. Travis, Github Actions, Circle etc.

Yeah. I'll get that done this week. 

My only real concern is that this list is very useful in indexing crystal libraries and bindings. Removing libs which haven't been updated in a couple breaking crystal versions gets makes in harder to access many useful libraries which could easily be fixed by a new contributor looking to use them. Rubygems has many gems which don't work with ruby 2.7 but they're still really useful for reference and can easily be fixed next time they're used.

I'd suggest that rather than removing them we move them to the bottom of the list under.

## Not currently maintained!

**Comment by Blacksmoke16** [comment]
@elorest That's not a bad idea.  Maybe we could throw them in a new file to keep them out of the README?  I'd like @veelenga's thoughts on this first tho.

Either way, the removed shards will be in version control so it wouldn't be hard to bring them back.

**Comment by veelenga** [comment]
@elorest @Blacksmoke16 this is a curated list of working shards. We want to guarantee they work. 

There are other resources to list/search across all shards which much more useful for described use case:

* http://shards.info/
* https://crystalshards.org/
* GitHub (i.e. https://github.com/search?q=language%3ACrystal+binding&type=Repositories)

**Comment by samueleaton** [comment]
been out of office for a while. Got pinged for https://github.com/samueleaton/sentry

It used so frequently at some large companies that we typically catch breaking changes pretty quickly. I can add CI to it but its not really a priority for me.

**Comment by Blacksmoke16** [comment]
@samueleaton Feel free to make a PR to add it back once it's added then.

**Comment by zatherz** [comment]
I am amused by the fact that you rejected the library despite it apparently being used in a lot of real places doing real work because it doesn't have a green PNG in its readme.

**Comment by Blacksmoke16** [comment]
If I allow that one then that starts a precedent that "oh my shard is used a lot so I shouldn't have to bother." 

If it's used by so many people I'm sure someone will take the 10 minutes it would take to setup CI and be done with it.

**Comment by veelenga** [comment]
@zathers Being not a part of this list doesn’t mean we think a shard is bad or unusable. Actually, that is great yours is doing real work and used in many places.

However, we want to control the list quality and ensure most of the entries are up to date and work with latest crystal. The most applicable way for us is some automation, since no one of us is able to verify each entry on a regular basis. 

That means each shard needs to have a CI build, which is also a good sign of a developer workflow. As simple as is, no green png in the readme is needed :)

If you disagree with the above, I can add your shard to the exception list. Don’t want to offense someone or reject any valuable effort.

**Pull request merged**
