### PR TITLE
Add "mxnet.cr"

### PR DESCRIPTION
**Pull request by toddsundsted**
Add bindings to [Apache MXNet](https://mxnet.incubator.apache.org/) DNN library.

### CODE REVIEW

**Comment by toddsundsted** [comment]
the NDArray and Symbol classes need trigonometric functions and then mxnet.cr works as a basic library for numeric/scientific computing, as well as machine learning. after than, I'm going to port over the Ruby Gluon code I wrote for [mxnet.rb](https://github.com/mrkn/mxnet.rb) -- it's already half finished but sitting on my laptop. at that point a diligent Crystal developer who wants to learn machine learning and DNNs can successfully complete most of the exercises in [Deep Learning The Straight Dope](https://gluon.mxnet.io/).

**Comment by veelenga** [comment]
@toddsundsted any update?

**Comment by toddsundsted** [comment]
i'm developing in a branch (https://github.com/toddsundsted/mxnet.cr/tree/gluon). i am planning to restructure the specs at the end of that work. weekly builds *should* be happening on Travis (https://travis-ci.org/toddsundsted/mxnet.cr). i'm a couple weeks away from merging that branch. i'll post here when that happens!

**Comment by veelenga** [comment]
@toddsundsted closing this because of inactivity. Be free to re-submit.

**Pull request closed without merging**
