### PR TITLE
Added markov shard to Algorithms and Data Structures

### PR DESCRIPTION
**Pull request by mccallofthewild**
- [x] Generally useful to the community
- I hope so :)
- [x] Functional
- Object Oriented actually ;)
- [x] Actively maintained
- You bet.
- [x] Stable
- As stable as a library written in an Alpha-stage language gets!
- [x] Documented
- I'd like to take this moment to thank the `crystal docs` command
- [x] Has tests (when possible)
- 100% tested code

### CODE REVIEW

**Comment by vladfaust** [comment]
Nice example of a situation when the list's curators **may** not be fully compliant with the functionality the PR subject brings. However, this looks good to me and this is why:

- Friendly README
- Great documentation @ http://www.mccallalexander.com/markov
- Appropriate code style
- Amazing (from the first glance) specs

There are some issues, though:

- No build badge. We don't know whether is the edge version is stable
- No releases (and no `version: ` in README). We don't know which version is stable. It's a good practice to do GitHub releases
- `docs` folder in the repo itself should be removed. I might suggest you need this folder for GitHub pages, however there are another ways. Refer to [this page](https://docs.travis-ci.com/user/deployment/pages/) and see example [.travis.yml](https://github.com/vladfaust/core.cr/blob/master/.travis.yml)

**Comment by RX14** [comment]
@vladfaust please don't spread your comments on a specific subject around random issues in a repository. @mccallofthewild likely has *no idea* what you're talking about.

**Comment by mccallofthewild** [comment]
@RX14 I might be missing some context here, but I assume this is a continuation of https://github.com/veelenga/awesome-crystal/issues/223 and https://github.com/veelenga/awesome-crystal/pull/219.

@vladfaust Thanks for pointing out the issues! Versioning/releasing is definitely a skillset I'm looking to improve. I'll fix those problems pronto.

**Comment by mccallofthewild** [comment]
Done!
 bitmoji

**Comment by RX14** [comment]
@mccallofthewild just a heads up, the version tag should be `v0.1.1` not `0.1.1`.

**Comment by mccallofthewild** [comment]
@RX14 Thanks, I looked into that and ended up deciding not to use the `v`. After reading through https://github.com/mojombo/semver/issues/204, it would seem that the `v` is not actually part of semantic versioning, but rather an optional prefix that certain communities/package managers decide to use. Seeing as the Crystal language itself doesn't use the `v` (https://github.com/crystal-lang/crystal/tags), I decided against it.

**Comment by RX14** [comment]
@mccallofthewild shards itself requires a `v` prefix to find versions. Crystal itself doesn't use `v` as a historical artefact that is hard to change, not to set an example.

**Comment by mccallofthewild** [comment]
Ah, gotcha... "the repository is expected to have version tags following a semver-like format, prefixed with a `v`" - https://github.com/crystal-lang/shards#usage

I'll change it! :)

**Comment by RX14** [comment]
I think there definitely needs to be a "shard guide" containing robust steps on how to go from an idea to a crystal shard.

**Comment by veelenga** [comment]
https://veelenga.github.io/make-your-own-shard-in-crystal-language/

This might need some improvements and additions, but at least something.

**Comment by mccallofthewild** [comment]
@RX14 @veelenga Given what I learned from this discussion, I put something together while building [my next shard](https://github.com/mccallofthewild/gdax). 

Welcome to [Crystal Shards 101](http://www.mccallalexander.com/crystal-shards-101/ )!
GitHub: https://github.com/mccallofthewild/crystal-shards-101

[Lots to be done](https://github.com/mccallofthewild/crystal-shards-101/projects/1), but it's a start. Let me know what you think!

**Comment by RX14** [comment]
@mccallofthewild I'd mention `crystal tool format` in the section on code style and the travis section.

**Comment by mccallofthewild** [comment]
@RX14 I'm personally not using `crystal tool format` right now, just because I like to put my method arguments on new lines and `crystal tool format` breaks this formatting.
E.g. 
```crystal
def my_method(
    my_arg : String,
    my_other_arg : Int32,
    another_arg : Array(String) = ["my string", "my other string"]
)
``` 
instead of 
```crystal
def my_method(my_arg : String, my_other_arg : Int32, another_arg : Array(String) = ["my string", "my other string"])
```
But it certainly wouldn't hurt to mention it! The Crystal Compiler is a wonderful tool altogether.
Thanks & good idea w/ the crystal-book PR. Will do.

**Comment by RX14** [comment]
@mccallofthewild you can certainly break up your call args into multiple lines and have it format...

I think
```cr
def my_method(my_arg : String,
              my_other_arg : Int32)
end
```
might work.

**Comment by RX14** [comment]
@mccallofthewild Actually, see https://github.com/crystal-lang/crystal/issues/1924 which is going to make it into the next `0.24.0` release. This should solve your formatter issue!

**Pull request merged**
