### PR TITLE
add promise, tasker and bisect

### PR DESCRIPTION
**Pull request by stakach**

### CODE REVIEW

**Comment by stakach** [comment]
@veelenga all good for a pull?

**Comment by veelenga** [comment]
@stakach well, it raises a couple of questions/suggestions from my side:

### Bisect

* please don't patch the standard library implicitly. Maybe better to allow requiring a separate file for that:

```
require "bisect/ext"
```

### Promise

* we alredy have a couple implementations of promises. I am not really happy to add libraries which bring the same purpose. Maybe you can explain what is the difference between "promise" and [promise.cr](https://github.com/jwaldrip/promise.cr)?
* please format the sources `crystal tool format`
* there are a couple of small code smells to be fixed. Here is a list:

<details>

```
promise git:master ❯ ameba                                                                                                                                                                                                                  
Inspecting 6 files.

F..F..

spec/promise_spec.cr:36:20
Lint/ShadowingOuterLocalVar: Shadowing outer local variable `value`

spec/promise_spec.cr:84:20
Lint/ShadowingOuterLocalVar: Shadowing outer local variable `value`

spec/promise_spec.cr:49:17
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:50:17
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:84:20
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:82:18
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:99:18
Lint/UnusedArgument: Unused argument `result`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:100:18
Lint/UnusedArgument: Unused argument `result`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:109:17
Lint/UnusedArgument: Unused argument `result`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:110:18
Lint/UnusedArgument: Unused argument `result`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:122:18
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:134:17
Lint/UnusedArgument: Unused argument `result`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:135:18
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:136:18
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:137:18
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:138:18
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:167:18
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:168:19
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:195:20
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:204:28
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:213:26
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:214:19
Lint/UnusedArgument: Unused argument `result`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:215:20
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:225:21
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:250:21
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:252:18
Lint/UnusedArgument: Unused argument `error`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:275:27
Lint/UnusedArgument: Unused argument `value`. If it's necessary, use `_` as an argument name to indicate that it won't be used.

spec/promise_spec.cr:342:9
Lint/UselessAssign: Useless assignment to variable `val1`

spec/promise_spec.cr:342:15
Lint/UselessAssign: Useless assignment to variable `val2`

spec/promise_spec.cr:375:9
Lint/UselessAssign: Useless assignment to variable `val1`

spec/promise_spec.cr:375:15
Lint/UselessAssign: Useless assignment to variable `val2`

spec/promise_spec.cr:386:9
Lint/UselessAssign: Useless assignment to variable `result`

spec/promise_spec.cr:414:9
Lint/UselessAssign: Useless assignment to variable `val`

spec/promise_spec.cr:426:9
Lint/UselessAssign: Useless assignment to variable `val`

spec/promise_spec.cr:4:1
Style/ConstantNames: Constant name should be screaming-cased: LOG, not Log

spec/promise_spec.cr:5:1
Style/ConstantNames: Constant name should be screaming-cased: WAIT, not Wait

src/promise/deferred_promise.cr:177:18
Lint/ShadowingOuterLocalVar: Shadowing outer local variable `result`

src/promise/deferred_promise.cr:177:18
Lint/UnusedArgument: Unused argument `result`. If it's necessary, use `_result` as an argument name to indicate that it won't be used.

Finished in 48.94 milliseconds

6 inspected, 38 failures.

```
</details> 

### Tasker

* again quite similar to [schedule.cr](https://github.com/hugoabonizio/schedule.cr)
* `crystal tool format`

**Comment by stakach** [comment]
Thanks for pointing out ameba - sweet tool!
I've updated all libraries with your recommendations.

Really we should replace promise.cr with promise for the following reasons:
* promise for the most part infers the response type (no need to specify the promise type if you don't want to - let the compiler work it out)
* has a generic base class so you can have multiple jobs and do something when those jobs complete or error without knowing the values those jobs are returning
* a promise chain can mutate the value class type

That last point is important. Promise.cr seems to indicate it can do this in its readme.
However it can't and the example in the readme doesn't work.

**Comment by stakach** [comment]
With Tasker it has the following advantages:

* It's possible to obtain the calculated values 
* it tries to minimize the number of active fibers
* it recalculates the delay times periodically if the delay time is large
  * important as a task that should run once a week will suffer from clock drift when run on schedule.cr
* supports CRON jobs with timezone support

**Comment by veelenga** [comment]
@stakach okay, let's remove the promise.cr from the list and we are good to do.

**Comment by RX14** [comment]
Shouldn't we tag @jwaldrip before we remove promise.cr?

**Pull request merged**
