### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by vladfaust**
Closes https://github.com/veelenga/awesome-crystal/issues/346

You can always re-add your shard by following https://github.com/veelenga/awesome-crystal/pull/351

### CODE REVIEW

**Comment by Schniz** [comment]
I wonder if there's a way to leverage Hacktoberfest to make all (or at least some) of these projects pass again 😸

**Comment by lucaong** [comment]
@vladfaust I managed to update https://github.com/lucaong/immutable to be compatible with latest Crystal `v0.26.1`. If your checks pass, you could skip the removal of this shard.

Thank you!

**Comment by hugoabonizio** [comment]
Should we give it some more time?

**Comment by vladfaust** [comment]
It's been 28 days since I've created initial issues in problem shards.

https://www.youtube.com/watch?v=ST2H8FWDvEA

**Comment by vladfaust** [comment]
The time has come, pull the trigger.

**Comment by veelenga** [comment]
Please rebase to latest develop and we're ready to go.

**Comment by hugoabonizio** [comment]
Thank you @vladfaust

**Pull request merged**
