### PR TITLE
Add android.cr

### PR DESCRIPTION
**Pull request by faustinoaq**
Hi @veelenga 

This PR adds 2 awesome shards by @ysbaddaden

1. [android.cr](https://github.com/ysbaddaden/android.cr) - Create Android applications using Crystal and the NDK
2. ~~[java.cr](https://github.com/ysbaddaden/java.cr) - Java Native Interface (JNI) bindings (and generator) for Crystal~~

### CODE REVIEW

**Comment by veelenga** [comment]
Hey. Thanks, but java.cr is already onto the list

**Comment by RX14** [comment]
android.cr has been unmaintained for ages, why add it to the list? It's a super cool demo but not really... useful?

**Comment by faustinoaq** [comment]
@RX14 I think is good to show android is present in crystal community as well. In fact `android.cr` is a use-case for java.cr (already in the list). So, saying it's _not really... useful?_, is a bit unfair for this great shard.

**Comment by veelenga** [comment]
@faustinoaq can you confirm `android.cr` is still alive? I am not able to setup/compile it. Both projects look abounded to me. Probably we have to remove `java.cr` from the list too.

\cc @ysbaddaden

**Comment by faustinoaq** [comment]
@veelenga I was able to compile the examples some months ago, I didn't tested it on most recent crystal versions yet, I think would be some compatibility issues, and the lack of guide/documentation :sweat_smile:

**Comment by veelenga** [comment]
@faustinoaq I have removed java.cr from the list. We can add both libraries back once they have some support. Thank you

**Pull request closed without merging**
