### PR TITLE
README: Add x_do.cr

### PR DESCRIPTION
**Pull request by woodruffw**

### CODE REVIEW

**Comment by hugoabonizio** [comment]
Hi @woodruffw! We have a policy in [contribution guidelines](https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md) which says:

- If you just created something, wait at least 30 days before submitting to give it some time to mature and ensure it's not just a publish-and-forget type of project

**x_do.cr** seems really useful, let's just wait some more days so others can use and test it. :smiley:

**Comment by woodruffw** [comment]
Made the spec pass as of `0.6.1` (there are still no tests, since testing `libxdo` requires X11).

**Comment by RX14** [comment]
Why is the tests having to run on X11 a problem?

**Comment by woodruffw** [comment]
> Why is the tests having to run on X11 a problem?

It's not a problem *per se*, I just haven't figured out a good way to do it. I'll probably set up [Xephyr](https://en.wikipedia.org/wiki/Xephyr) or something similar, since I don't want my local X11 installation to affect the tests/coverage (I don't run a fully ICCCM compatible WM).

**Comment by hugoabonizio** [comment]
Maybe this link can help? https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

**Comment by woodruffw** [comment]
Thanks for the link, @hugoabonizio. Xvfb looks much better than Xephyr for this task.

**Pull request merged**
