### PR TITLE
Strikethrough of dead web frameworks

### PR DESCRIPTION
**Pull request by bigtunacan**
For the list to continue to be awesome we need to cleanup projects that aren't supported.  The web frameworks I've have crossed off here haven't been updated in at least a year and we probably don't want people wasting time going there.

### CODE REVIEW

**Comment by veelenga** [comment]
I was thinking about such a cleanup for a while. Seems this is a time to do it :)
Please remove those entries you marked and I will try to take care of other sections.

Thanks in advance

**Comment by RX14** [comment]
@veelenga I think anything not updated in a yearis unlikely to work with current crystal, and anything not updated since december needs a check that it still compiles.

**Comment by veelenga** [comment]
@RX14 I agree with that. A resource that is not updated for a year or so is a good candidate for removal. But I don't think we have to remove anything that just does not work now. Well, at least because:

1. It could be updated sooner or later by the maintainer.
2. A great example of what could be implemented (reworked).

so still could be useful for users.

I will try to filter out unuseful for now entries and remove it ;)

**Comment by bigtunacan** [comment]
@veelenga Cool.  Updated to just delete those outdated ones.

**Comment by veelenga** [comment]
Thank you!

**Pull request merged**
