### PR TITLE
Migrate some repositories

### PR DESCRIPTION
**Pull request by Nephos**
Hi,

I'm starting to get my repositories out of github, so I will update them on my own domain.

### CODE REVIEW

**Comment by Nephos** [comment]
I was just moving some files for my migration (I changed from gogs to gitea). I've just finished to stabilize everything.

**Comment by veelenga** [comment]
@Nephos some of your repos have incorrect installation info (pointing to github):

https://git.sceptique.eu/Sceptique/CrystalEmail#installation

**Comment by Nephos** [comment]
I update most of it

* I do not delete the github repositories
* I only update the new ones

**Comment by veelenga** [comment]
Are you going to support repos on GitHub and the custom domain?

If not, please update all of them. Imagine this scenario:

1. Repo on a custom domain has new features
2. Repo on a custom domain has GitHub reference in the installation instructions
3. User pulls the repo from the GitHub and can't see your new feature there

**Comment by Nephos** [comment]
Yeah I started the update yesterday because of that. I must finish with transfer_more and some others

**Comment by veelenga** [comment]
@Nephos Could you suggest how we can control whether your shard still works or not? Will we have a link to the CI build?

We usually request periodic CI builds. That's because Crystal often releases breaking changes and we don't want to keep outdated (and abundant) repos in the list.

**Comment by Nephos** [comment]
I did not plan do make such thing, but i'll take a look at travis CI or something to see if I can enable something automatic.

**Comment by RX14** [comment]
Lets either merge this or remove the repos. Leaving broken and outdated links is the worst of both worlds.

I suggest we just merge this PR as-is, removing the repos is harsh.

**Comment by veelenga** [comment]
Makes sense

**Pull request merged**
