### PR TITLE
Add devdocs.io

### PR DESCRIPTION
**Pull request by faustinoaq**
This PR adds devdocs.io

http://devdocs.io/crystal/ is a useful API & Documentation Browser.

### CODE REVIEW

**Comment by faustinoaq** [comment]
@hugoabonizio Yeah, I need to do a PR here 👉 https://github.com/Thibaut/devdocs but I'll wait for `0.24.0`, seems to be pretty close to be released.

**Comment by tbrand** [comment]
I'm not sure the devdocs.io should be in the **Tool** category...? 🤔

**Comment by faustinoaq** [comment]
@tbrand I know devdocs isn't crystal exclusive, but is a useful documentation tool, What category do you think it should be?

**Comment by RX14** [comment]
It's not really a crystal project, it just happens to have crystal on it. I'm not sure we should include it.

**Comment by veelenga** [comment]
@RX14 there is already a bag of not-really-crystal projects/resources in the list:

https://github.com/veelenga/awesome-crystal#devops
https://github.com/veelenga/awesome-crystal#editor-plugins
https://github.com/veelenga/awesome-crystal#shell-plugins
https://github.com/veelenga/awesome-crystal#official-documentation-translations

and IMO it actually makes the list more useful. Personally, i would definitely like to see  devdocs here as well.

@faustinoaq let's put it onto the [Resources](https://github.com/veelenga/awesome-crystal#resources) section.

**Comment by veelenga** [comment]
@hugoabonizio the [0.23.0..0.23.1](https://github.com/crystal-lang/crystal/milestone/23?closed=1) doc diff is not really big. And I saw a lot of people refer to devdocs so it is more or less popular. Can we merge this without upgrade to `0.24.0`?

**Comment by hugoabonizio** [comment]
@veelenga I think this can seen confusing to newcomers, on the other hand this will probably be replaced by `0.24.0` soon. Let's merge.

**Pull request merged**
