### PR TITLE
Refactor CLI

### PR DESCRIPTION
**Pull request by Blacksmoke16**
* Support transferred repos
* Use more OOP patterns to make it easier to maintain
* Fix Crystal deprecations
* Use Log module instead of pp and puts
* Support `1.0.0`

### CODE REVIEW

**Review by veelenga — APPROVED** [review]
💪 I feel like we would need to cover this with specs someday to be future-proof.

**Comment by Blacksmoke16** [comment]
@veelenga Prob wouldn't be too bad, but would deff want to implement it with `webmock`.  Can save that for a follow up PR, but it should at least be more testable now than it was.

**Comment by veelenga** [comment]
@Blacksmoke16 it is ready to be merged. We will add tests later

**Comment by Blacksmoke16** [comment]
@veelenga But we can't, needs another approval (unless you have admin rights or something).

**Comment by veelenga** [comment]
Sorry, my bad.

**Pull request merged**
