### PR TITLE
Add larimar

### PR DESCRIPTION
**Pull request by Wozzy06**
add larimar library, a simple property manager

### CODE REVIEW

**Comment by RX14** [comment]
the spec is https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#load(java.io.Reader)

**Comment by Wozzy06** [comment]
ok, I'll make an update soon to implement the specs

**Comment by veelenga** [comment]
Hey @Wozzy06 what's the status here?

**Comment by veelenga** [comment]
@Wozzy06 be free to re-open PR when you are ready.

**Pull request closed without merging**
