### PR TITLE
Added DOCX library reference

### PR DESCRIPTION
**Pull request by aristotelesbr2014**
## Link

https://github.com/aristotelesbr2014/docx_cr_converter

## Checklist
* [x] - Shard is at least 30 days old.
* [x] - Shard has CI implemented.
* [x] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).

### CODE REVIEW

**Review by veelenga — COMMENTED** [review]
Thanks for your contribution. Seems like the last commit was done 6 months ago and there are still some TODOs in readme. Could you please elaborate on how the project is going to be evolved?

**Comment by aristotelesbr2014** [comment]
The project already meets a demand. TODOs are common features among libraries that do this job. I believe it depends on each project. Perhaps if the library has visibility, someone else will be interested in contributing.

TODOs are only perspective. :)

**Comment by Blacksmoke16** [comment]
Also looks like the latest build failed: https://travis-ci.org/github/aristotelesbr2014/docx_cr_converter/builds/725063539.

I think a period build also needs to be setup.  See https://docs.travis-ci.com/user/cron-jobs/.

**Comment by aristotelesbr2014** [comment]
@Blacksmoke16 Done!

**Review by Blacksmoke16 — APPROVED** [review]

**Review by veelenga — APPROVED** [review]

**Pull request merged**
