### PR TITLE
Add elorest/cry

### PR DESCRIPTION
**Pull request by docelic**
Add elorest/cry - Ability to execute crystal code in a fashion similar to pry edit.

### CODE REVIEW

**Comment by veelenga** [comment]
Thanks for your contribution. I'm not sure regarding this. AFAIK this was just an experiment to add `exec` command to Amber see https://github.com/amberframework/amber/pull/371

/cc @elorest

**Comment by tbrand** [comment]
Agree to @veelenga for me.

**Comment by docelic** [comment]
@elorest was aware I sent this for inclusion.
This tool can be used standalone (it is in no way specific or related to Amber), and also we are doing some further improvements/features to it which won't be in 'amber exec'.

**Comment by elorest** [comment]
What @docelic said. :arrow_up:

**Comment by elorest** [comment]
This has similar functionality to `amber exec` but is intended to be used for quickly iterating on code in a similar fashion to `pry edit` in ruby.

**Comment by elorest** [comment]
@veelenga I noticed that this has some similarity to your `vicr`. Differences being that yours can load files from http and mine can easily reopen previous runs similar to `pry` in ruby. Also there's a log to make it easy to keep track of what you ran in the past with the results.

I believe that `vicr` forces users to use vim (which any sane developer should be :smile: ), while `cry` defaults to vim but lets users choose their editor.

At some point we might want to try to merge that functionality.

**Comment by veelenga** [comment]
> At some point we might want to try to merge that functionality.

@elorest I completely fine to do that 👍 

@tbrand @hugoabonizio @RX14 please leave yours approves/rejects. Should we merge or not.

**Comment by elorest** [comment]
For now this is a tool that quite a few people use so I think it should be merged in to awesome crystal for now. After all there are like 8 command line parsers already lol.

**Pull request merged**
