### PR TITLE
Add crystal_on_steroids

### PR DESCRIPTION
**Pull request by werner**
Hi, I'd like to add my project to the list.

Best regards.

### CODE REVIEW

**Comment by RX14** [comment]
I tend to dislike "stdlib extension" projects because they tend to consist of either ideas which should be PRed into the stdlib, or which are not in the stdlib for good reason. That being said, I won't pretend that our opinion isn't sometimes wrong, so i'll give this project a solid meh.

**Comment by werner** [comment]
@RX14 I understand what you're saying, in fact I indeed have received the same critique before, however, Active Support exists for a reason, and it's useful to a lot of people, so, this might not look useful to you, but I'm sure it will be for a lot of others.

Regarding Array#split, I just fixed it to replicate it to what Active Support does, it uses a dup version of self. https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/array/grouping.rb#L94

**Comment by veelenga** [comment]
@werner Active Support lives mostly in terms of Rails (and maybe some other web frameworks). I don't think it is widely used by plain ruby apps/libs. `crystal_on_steroids` doesn't have such a framework, so for me it looks like a [powerpack](https://github.com/bbatsov/powerpack), which is not seems to be popular.

Nevertheless, I still think `crystal_on_steroids` is a good addition to the list even if it is not globally used. It has small examples how to implement those methods and maybe will prevent someone to create another extension.

@RX14 what is your position, merge/reject or what?

**Comment by RX14** [comment]
Do we want this to be a list of acceptable libraries or a list of awesome libraries? This library is acceptable. But its not awesome. It just had a bit too little benefit, a lot of non-typesafe (ruby) design, and likely bad performance. 

I vote no but there's a lot of libraries already on the list i'd vote no for. So me voting no raises that problem too.

**Comment by werner** [comment]
@veelenga Yeah, you're right!, I think it looks like more to powerpack than Active Support, I just wanted to have some cool methods that are included in Rails too.

@RX14 I have no problem with this PR being rejected if it's not an awesome shard, however I'm really concern about the bad performance claim, could you please tell me why you think that? and what methods are non-typesafe?, I'm willing to do the necessary refactoring.

**Comment by RX14** [comment]
@werner Here's a list of nitpicks:
- The `Array.define_order` macro defines a method which uses `@buffer` and checks `@size` automatically? Why? Why not just have:
  ```cr
  def second
    self[1]
  end
  
  # etc...
  ```
  it'll just be inlined to get the same code as before and is *much* cleaner. A macro here is probably worse than just copy and paste too, but that's just my opinion.
- `Array#rest` has incorrect semantics: `[1, 1, 1].rest == [] of Int32` when it should be `[1, 1]`. This is because of the silly way you've implemented it:
- `Array#rest` creates 3 array when it should only create 1: it first calls `dup` which allocates, then it creates an array with just the first element in, then it calls `-` to get the (incorrect) result. The correct naive implementation is:
  ```cr
  def rest
    result = Array(T).new(size - 1) 
    1.upto(size - 1) do |i|
      result[i - 1] = self[i]
    end
    result
  end
  ```
  but an even faster way (because `Array(T).new(size, &block)` can elide some bounds checks and we use `unsafe_at`) is
  ```cr
  def rest
    Array(T).new(size - 1) { |i| unsafe_at(size + 1) }
  end
  ```
  except for the fact that we already have a fantastically optimized implementation of `Array#[](start, count)` which makes the fastest *and simplest* method just:
  ```cr
  def rest
    self[1, size - 2]
  end
  ```
- `Array#split` is alright, I got confused and thought it could return a tuple (it can't, the number of result values can be more than 2). You could probably get it a lot faster by using the same `Array#[](start, count)` method and not using `dup` and mutating the array (`shift` is *not* cheap! it has to move every element in the array). Methods in `Array/Indexable/Enumberable` rarely call `dup` because it's very often not the fastest way to implement things.
- `Enumerable#many?`'s implementation is a little weird, involving modifying `count` inside an `any?` block. I suggest you simply use `each` and `return true if count > 1` with a `false` as the default case.
- `Enumerable#many?` (without a block) won't count falsey elements. Which is fine, it's just not what the documentation says. If the doc was correct, the method implementation would just be `size > 1`.
- Why does `pluck` use `item[]?` with multiple keys but `item[]` when using a single key? It should either return nil when the key doesn't exist, or not. I suggest defining `pluck` and `pluck?`.
- Why does `compact` use `select` with `!value.nil?` and `compact!` use `reject!` with `value.nil?`? It makes no difference but it makes no sense either.
- A lot of doc comments still have rubyisms like `@return`.
- `Nil#includes?` is just there to avoid the type system. `nil.includes?` is a type error in crystal, and monkeypatching it *not* to be here is just avoiding handling nil properly.
- `String#blank?` was added to crystal 11 months ago and should be removed because the stdlib has an optimized implementation.
- `String#remove?` isn't tested with multiple patterns. And I can see why, the spec would fail as far as I can see.
- `String#truncate` should use named args instead of an options hash. Yet more evidence there were blindly copy-pasted from activesupport.
- `String#truncate` doesn't need to return `dup` because strings are immutable so you can simply return `self`. Luckilly `String#dup` is just `self` anyway.
- In `truncate_words` `Regex === sep` is a rubyism, use `is_a?` which actually performs type restrictions.
- `squish` could be rewritten using a string builder and `String#each_char` and `Char#whitespace?` and be faster,
- `prev_day` should really be `self.at_beginning_of_day - 1.day`, and ditto for `next_day`.
- `today?` can be implemented by:
  ```cr
  now = Time.now
  now.at_beginning_of_day <= self <= now.at_end_of_day
  ```

**Comment by werner** [comment]
@RX14 thanks, I appreciate the suggestions and I'll make the needed fixes.

 @veelenga I suggest a rejection of this PR until I make the fixes suggested by @RX14, I'd do it myself but I don't know how.

**Pull request closed without merging**
