### PR TITLE
Added jwt.cr

### PR DESCRIPTION
**Pull request by rogeriozambon**
[jwt.cr](https://github.com/rogeriozambon/jwt.cr)

Added to **Networking** section

- [x] Tests pass (`crystal spec`)
- [x] Description of the entry is clear and concise. There is no excessive information like
      **"... for Crystal programming language"**,
      **"... for Crystal"**,
      **"... written in Crystal"** etc.

### CODE REVIEW

**Comment by RX14** [comment]
Why another JWT shard? Why not contribute to the existing one?

**Comment by rogeriozambon** [comment]
I think we can have a bunch of libraries, with different implementations, but who needs to use will decide which one is better for your case. If this new implementation does not fit in this list, there are no problems.

**Comment by vladfaust** [comment]
This is a nice example of the topic we have these days! This PR is useless due to:

- No new functionality comparing to [jwt](https://github.com/crystal-community/jwt)
- Even less functionality than [jwt](https://github.com/crystal-community/jwt) - no iss, sub, aud asserts
- Bad formatting
- Lesser documentation

The only difference I see is splitting the code into multiple files. This may be a better practice, SOLID etc., but JWT is strictly utility library with standards in implementation, it never needs to be expanded or so.

**Comment by rogeriozambon** [comment]
Alright, thanks guys!

**Comment by drujensen** [comment]
@rogeriozambon we want to avoid duplicate efforts and wasted energy on reinventing the wheel.  The hope is to avoid the npm hell that the JS community is going through.

If this does something different or provides a new way of doing something and you already tried to contribute your idea to the existing project and they rejected it.  Fine, you have done your due diligence and this should be accepted.

But if that is not the case, consider contributing your ideas to the existing project instead.

**Comment by vladfaust** [comment]
@rogeriozambon I'm sorry if I've offended you. But @drujensen is right. Invest your potential into something new or make better something what's already exists! :blue_heart:

**Comment by veelenga** [comment]
Oh, guys, you are very welcomed to the newcomers to Crystal. Didn't you forget that this is an open source and the developers are doing their work for free? Don't you think that critic is not the best approach to develop a community?

@vladfaust  I can show the similar example of the topic we have these days: https://github.com/veelenga/awesome-crystal/pull/212. Why is this situation different from the original? Because your code is formatted? 

@drujensen Crystal is not so popular as javascript and probably will never be. I think we don't have to worry about npm hell, at least for now.

Calm down guys and think how to make Crystal valuable instead of pushing off everyone who did not format code, created a similar project or wrote a shard with a small codebase. 

https://github.com/crystal-community/jwt does not have a maintainer. @rogeriozambon are you interested in a maintaining this repository?

**Comment by RX14** [comment]
@vladfaust please think about how your comments may come across to other people before commenting. Constructive criticism is fine, but your criticism sometimes isn't worded constructively. It takes just a few seconds to reword your comment, and it usually makes other people much more recipient to your comment.

@rogeriozambon Duplicate libraries are bad, but somewhat acceptable usually. However, jwt is particularly sensitive because it's used for security. For that reason, the downsides of writing a new shard are much higher because bugs might be spotted and fixed in other implementations.

**Comment by drujensen** [comment]
@veelenga With any non profit or OS community, it's wise to try and specify the best way a contributor can be of most help.  I hope I didn't come across that we are not appreciative of the effort but I would rather discuss this with a new contributor now rather than later.  

@rogeriozambon please forgive me if I sounded harsh.  I'm looking forward to seeing you contribute more! Hopefully you will take on the JWT project. 🥇

**Pull request closed without merging**
