### PR TITLE
Add debug.cr shard

### PR DESCRIPTION
**Pull request by Sija**
Adds [debug.cr](https://github.com/Sija/debug.cr) shard to the `Tools` section - btw, what do you think about creating new section titled `Debugging`?

### CODE REVIEW

**Comment by Sija** [comment]
@veelenga done!

**Comment by Sija** [comment]
Ready to merge?

**Comment by veelenga** [comment]
Not yet, cause it does not match the guidelines yet: https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md

**Comment by Sija** [comment]
@veelenga oh, it's about this 30 days rule? I understand the reasoning behind it, yet IMO it's too unflexible and artificial - I've seen projects years old which were far from being actively-maintained, mature or finished and days-old which are complete and mature enough to already use them. Basis for _debug.cr_ is code from my another shard _gphoto2.cr_, which exists in the codebase for 2+ yrs for instance.

**Comment by veelenga** [comment]
Please be free to propose a more flexible way to filter out "one-day" projects (i.e. created, submitted and abondoned). For now, I would prefer to stick to the current approach.

**Comment by Sija** [comment]
I'd just stick to the quality-based rules instead of time-based - if all of them would be satisfied than time-based constraints wouldn't matter that much - say, having a working, well-tested and functional shard which is week old should be enough for inclusion - OTOH half-baked, lacking specs, shard which is 3 months old shouldn't be considered as a candidate.

**Comment by veelenga** [comment]
Well, we do exactly the same: quality rules first, then 1 month of time for maturity. The difference in what you say is to wait 1 week instead?

**Comment by Sija** [comment]
I'd just skip the time-based requirement and focus moar on the quality side :)

**Comment by Sija** [comment]
Thanks, I appreciate it!

re:

> Also, please be sure to add periodical builds to your shard :)

They're already set up, it's a part of my standard workflow with Travis CI :)

**Pull request merged**
