### PR TITLE
Add JSON to Crystal

### PR DESCRIPTION
**Pull request by watzon**

### CODE REVIEW

**Comment by veelenga** [comment]
Nice one. Is this written in Crystal?

**Comment by veelenga** [comment]
I found few issues with it:

1. I can't type/edit the json, because all my inserts are reverted. 
For example, if you want to type `{id: 'test'}` you get `}'tset':di{`

2. Top level arrays in JSON are not properly processed:

image

**Comment by watzon** [comment]
It's not written in Crystal since the goal is to run it in the browser, but I am thinking about writing a shard to do the same thing. In response to your issues

1. I'm working on a fix for this, but it's going to require figuring out a different solution for code highlighting or removing the highlighting from the json which I don't want to do. Currently it has to redo the highlighting everytime a change is made which messes with the ability to just type, the instructions do say paste though.

2. I actually found this yesterday before I went to sleep. I should have a fix up today.

3. I considered using Nil, but that seems kind of pointless since that value then can't contain anything and chances are it does have a type. JSON::Any at least encompasses Nil and everything else.

Thanks for checking it out!

**Comment by watzon** [comment]
Oh and the repo https://github.com/watzon/json-to-crystal

**Comment by watzon** [comment]
Ok 1 and 2 are fixed. I still don't like the idea of using Nil as a type in place of JSON::Any though.

**Comment by veelenga** [comment]
Let's merge it. Be free to discuss it in this thread

**Comment by watzon** [comment]
As far as the `crystal tool format` issue I've thought about it, but it's going to be a royal pain. With the json-to-go tool they have a javascript version of go-fmt that handles the formatting.

**Comment by RX14** [comment]
@watzon You don't have to actually use `crystal tool format`, just try to match it's output in the simplest cases. There's only very very limited constructs you're generating in the generator, so you only have to copy a very few simple behaviours and rules from the formatter.

I don't think it should be very hard.

**Comment by veelenga** [comment]
@watzon The tool is not available anymore. Should we remove from the list?

**Pull request merged**
