### PR TITLE
add simple_rpc

### PR DESCRIPTION
**Pull request by kostya**
## Link
(https://github.com/kostya/simple_rpc

## Checklist
* [+] - Shard is at least 30 days old.
* [+] - Shard has CI implemented.

### CODE REVIEW

**Review by veelenga — APPROVED** [review]

**Comment by Blacksmoke16** [comment]
@kostya Could use a rebase on master.  Pretty sure CI would fail due to it not being in ABC order.

**Comment by Blacksmoke16** [comment]
@kostya Just a heads up your CI seems broken.  TravisCI is pretty much dead these days so I'd suggest migrating to GH Actions: https://crystal-lang.org/reference/guides/ci/gh-actions.html.

**Comment by kostya** [comment]
fixed

**Comment by Blacksmoke16** [comment]
@kostya Thanks, could you also add a periodic CI build?

**Comment by kostya** [comment]
added

**Review by Blacksmoke16 — APPROVED** [review]

**Pull request merged**
