### PR TITLE
Add validations.cr

### PR DESCRIPTION
**Pull request by vladfaust**
Compared with [accord](https://github.com/neovintage/accord), [validations.cr](https://github.com/vladfaust/validations.cr) aim at inline attributes validation other than defining a separate `def validate` method.

Compared with [denetmen](https://github.com/izniburak/denetmen), [validations.cr](https://github.com/vladfaust/validations.cr) is an entity mixin other than separate objects patcher.

It's still a PR and can be declined if community decides it's not needed.

### CODE REVIEW

**Comment by veelenga** [comment]
Let's create a separate section for those three.

**Comment by vladfaust** [comment]
So, Misc / Validation? Or the highest level Validation?

**Comment by veelenga** [comment]
Highest level "Validation" pls

**Comment by vladfaust** [comment]
I wonder if such descriptions are appropriate:

## Validation
 * [accord](https://github.com/neovintage/accord) - Shareable validations relying on `Validator` objects and `def validate` method
 * [denetmen](https://github.com/izniburak/denetmen) - Monkey patch validations, e.g. `String#email?`
 * [validations](https://github.com/vladfaust/validations.cr) - Validations mixin, e.g. `validate @name, size: (1..10)`

**Comment by vladfaust** [comment]
For me, it's not clear what does "shareable validation library" even mean. Also, "micro check" makes much less sense than "monkey patching". It's my opinion. If you're sure about such possible confusions, leave " :+1: "

**Comment by hugoabonizio** [comment]
In my opinion we should just stick with the current descriptions.

**Pull request merged**
