### PR TITLE
add Grip

### PR DESCRIPTION
**Pull request by grkek**
## Link
https://github.com/grkek/grip

## Checklist
* [X] - Shard is at least 30 days old. (It is an 8 day old Kemal fork which has lots of changes implemented and gets updated everyday-ish)
* [X] - Shard has CI implemented.
* [X] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
Sorry I can't approve this.

>  Shard is at least 30 days old. (It is an 8 day old Kemal fork which has lots of changes implemented and gets updated everyday-ish)

You'll need to wait the 30 days.

**Comment by Blacksmoke16** [comment]
@grkek Can you make sure you have periodic builds setup correctly?  I don't see any in the build history.

**Comment by grkek** [comment]
> @grkek Can you make sure you have periodic builds setup correctly? I don't see any in the build history.

I am not quire sure what you mean, but I cloned the Travis CI configurstion from kemal which seems to be okay.

**Comment by Blacksmoke16** [comment]
@grkek See https://docs.travis-ci.com/user/cron-jobs/

**Comment by grkek** [comment]
> @grkek See [docs.travis-ci.com/user/cron-jobs](https://docs.travis-ci.com/user/cron-jobs/)

@Blacksmoke16 Okay the cron jobs are added and they run daily, thank you for the link.

**Comment by grkek** [comment]
> ante

@hugoabonizio I hand-test the framework instead of using the specs since I am not familiar with specs, I will add them later on which will involve copying things from Kemal and modifying them.

**Comment by grkek** [comment]
> Well, there are actually no specs so the CI itself isn't providing any guarantee that the project is working. In my opinion this project is quite interesting and some specs would add a lot.

@hugoabonizio Added some specs, review again please.

**Pull request merged**
