### PR TITLE
Add crinder

### PR DESCRIPTION
**Pull request by c910335**
I made this shard for speeding up the development of Web API.

Added to **Data Formats** section:

* [crinder](https://github.com/c910335/crinder) - Class based json renderer

I hope this will also help other Web API developers.
Thanks.

### CODE REVIEW

**Comment by c910335** [comment]
@hugoabonizio Done!

**Comment by c910335** [comment]
@veelenga 
Can you give an example why it is better to use composition rather than inheritance?
Inheriting from other classes causes confusion and may have side effect, in my opinion.

**Comment by hugoabonizio** [comment]
@c910335 Adding to the discussion: https://stackoverflow.com/a/1282895

**Comment by HCLarsen** [comment]
I agree that using it as a mixin is more practical than using inheritance. The reason goes back to why you'd use one or the other in any situation.

Inheritance is used when you want to instantiate something more specific than its superclass. When reading it out loud, it should make sense to say "the subclass is a type of its superclass." For example, an employee would be a subclass of a person, because an "employee is a type of person."

On the other hand, modules and mixins are used when you want to add a certain functionality. That's why so many mixin modules have the -able suffix in their name. For example, I want to add comparison functionality to my employee class, so that we can sort them by position.

**Comment by c910335** [comment]
I still think it should be a class after reading above all, at least in this case.
Or maybe **abstract class** would be better.

**Comment by veelenga** [comment]
@c910335 [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) is one of the known principles of OOP. Imho, from my experience, the developer should choose composition as often as he can. 

The example you ask about is simple: need to inherit from two classes. Let's say, someone would need to save dynamic renders in a database:

```crystal
class TodoRenderer < Granite::ORM::Base
  include Crinder::Base

  adapter pg
 
  field state : String # new/in_review/active
  field name : String  # name of the renderer
  field fmt : String   # format of the rendering

  # business logic goes here
end

TodoRenderer.last.render(Todo.last)
```

This is just a suggestion and not a change request. Inheritance would work in most cases anyway. Good luck with your lib 👍

**Comment by RX14** [comment]
These should be mixin modules, not superclasses. Serialization is a topic which is typically orthogonal to a class's main intent, and many people will want to have inheritance hierarchies where multiple items in the hierarchy are serializable. Both practically and semantically, inheritance is the wrong tool for the job here.

Inheritance instead of modules doesn't even gain you anything at all, as the base class cannot be instantiated on it's own and it doesn't define any common instance variables. Please, use `include` and modules here.

**Comment by c910335** [comment]
Separate renderer from model is the purpose of crinder. It makes them clean and not confusing. Thus I chose inheritance instead of composition to avoid merging them.

**Comment by HCLarsen** [comment]
Wait, so the idea behind crinder is that it does the rendering for an external class, not its subclass?

**Comment by c910335** [comment]
@HCLarsen Yes.

**Comment by RX14** [comment]
Oh yeah nevermind. You're right, I read the readme wrong.

**Comment by HCLarsen** [comment]
Wow. That's a very interesting way of doing it.

**Pull request merged**
