### PR TITLE
Round three of erroneous shard removal

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Wraps up the erroneous shard removal started in #457, and #453.  Removes shards that have CI, but do not have periodic builds (CI hasn't ran in more than 30 days).  It's also possible that some shards do not have periodic builds, but CI has ran (due to a commit/release etc); these are not accounted for in this PR. I still need to go through them, so the list is currently not final.  Will also want to revisit the categories, as a good amount are now empty.

Once this is merged, we'll want to determine the CI strategy for keeping the list up to date; probably running the `./bin/cli` script in CI once every n days.

### Setting up Periodic builds
* TravisCI - https://docs.travis-ci.com/user/cron-jobs/
* GH Actions - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
* CircleCI - https://circleci.com/docs/2.0/configuration-reference/#schedule
* DroneCI - https://blog.drone.io/drone-1/#cron-scheduling
* GitLab - https://docs.gitlab.com/ee/user/project/pipelines/schedules.html

### Removed Shards
https://github.com/0x73/hoop
https://github.com/CodeSteak/Nuummite
https://github.com/CorbanR/ansible-crystal
https://github.com/DanSnow/crystal-binary_parser
https://github.com/EvanHahn/crystal-helmet
https://github.com/MakeNowJust/crystal-diff
https://github.com/MakeNowJust/crustache
https://github.com/Meoowww/Crirc
~https://github.com/RX14/predict.cr~
~https://github.com/RX14/fast_irc.cr~
https://github.com/SuperPaintman/response-time
https://github.com/SuperPaintman/ulid
https://github.com/SuperPaintman/ms
https://github.com/SuperPaintman/crystal-ctags
https://github.com/SuperPaintman/request-id
https://github.com/SuperPaintman/serve
https://github.com/TPei/circuit_breaker
https://github.com/TPei/crystal_openfaas
https://github.com/TPei/progress_bar.cr
https://github.com/TamasSzekeres/cairo-cr
https://github.com/TamasSzekeres/asound-cr
https://github.com/TamasSzekeres/x11-cr
https://github.com/TobiasGSmollett/fluent-logger-crystal
https://github.com/TobiasGSmollett/hash_ring
https://github.com/TobiasGSmollett/crystalg
https://github.com/abvdasker/crystal-linked-list
https://github.com/aca-labs/terminimal
https://github.com/akiicat/m3u8
https://github.com/ambercommunity/mongo.cr
https://github.com/anicholson/gopher.cr
~https://github.com/axvm/cake~
https://github.com/beanieboi/aws-signer.cr
https://github.com/benoist/terminal_table.cr
https://github.com/blacksmoke16/CrSerializer
https://github.com/blocknotes/magickwand-crystal
https://github.com/blocknotes/gumbo-crystal
https://github.com/blocknotes/kemal-rest-api
https://github.com/blocknotes/wkhtmltopdf-crystal
https://github.com/blocknotes/curl-crystal
https://github.com/bmulvihill/dispatch
https://github.com/cable-cr/cable
~https://github.com/chris-huxtable/syslog.cr~
~https://github.com/chris-huxtable/atomic_write.cr~
~https://github.com/chris-huxtable/config.cr~
~https://github.com/chris-huxtable/front_matter.cr~
~https://github.com/chris-huxtable/pledge.cr~
https://github.com/comandeo/syslog.cr
https://github.com/comandeo/crystal-memcached
https://github.com/creadone/device_detector
https://github.com/crystal-community/toml.cr
https://github.com/crystal-community/leveldb
https://github.com/crystal-community/msgpack-crystal
https://github.com/crystal-community/cossack
https://github.com/crystal-community/hardware
https://github.com/crystal-community/bloom_filter
https://github.com/crystal-community/timecop.cr
https://github.com/crystal-lang/crystal_lib
https://github.com/crystal-lang/html_builder
https://github.com/crystal-lang-tools/vscode-crystal-lang
https://github.com/crystal-loot/exception_page
https://github.com/danielpclark/keyer_cr
https://github.com/ddfreyne/glove
~https://github.com/delef/geoip2.cr~
https://github.com/dhruvrajvanshi/crz
https://github.com/dhruvrajvanshi/crystal-futures
https://github.com/didactic-drunk/sodium.cr
https://github.com/didactic-drunk/zstd.cr
https://github.com/diggersheep/warden
https://github.com/dlanileonardo/sendgrid.cr
https://github.com/docelic/fluence
https://github.com/emancu/crotest
https://gitlab.com/ezrast/crometheus
https://github.com/faustinoaq/kemal-watcher
https://github.com/faustinoaq/sentry-run
https://github.com/faustinoaq/watcher
https://github.com/fazibear/tensorflow.cr
https://github.com/felipeelias/crystal-github
https://github.com/fridgerator/google_maps_api
https://github.com/gdonald/blackjack-cr
https://github.com/gdotdesign/cr-dotenv
https://github.com/geppetto-apps/crow
https://github.com/gewo/bugsnag.cr
https://github.com/huacnlee/html-pipeline
https://github.com/icyleaf/gitlab.cr
https://github.com/icyleaf/wasp
https://github.com/imdrasil/hermes.cr
https://github.com/imdrasil/sam.cr
https://github.com/impatienttraveller/json-tools
https://github.com/isaced/pangu.cr
https://github.com/izniburak/query-builder
https://github.com/izniburak/denetmen
https://github.com/izniburak/turkish-number
https://github.com/j8r/cride
https://github.com/j8r/clicr
https://github.com/jeromegn/bson.cr
https://github.com/jeromegn/slang
https://github.com/jeromegn/kilt
https://github.com/johnjansen/clamp
https://github.com/jwoertink/kave
https://github.com/jwoertink/fez
https://github.com/kemalcr/kemal
https://github.com/kemalcr/kemal-session
https://github.com/kemalyst/kemalyst-generator
https://github.com/konovod/linalg
https://github.com/libpixel/libpixel.cr
https://github.com/lirith-engine/lirith
https://github.com/luckyframework/carbon
https://github.com/luckyframework/habitat
https://github.com/luckyframework/lucky_flow
https://github.com/luislavena/radix
https://github.com/maiha/redis-tsv.cr
https://github.com/maiha/hq.cr
https://github.com/manastech/crystal_slack
https://github.com/marceloboeira/bojack
https://github.com/measurechina/eventql-crystal
https://github.com/meew0/discordcr
https://github.com/metaware/flipper
https://github.com/mjago/soundfile
https://github.com/mosop/teeplate
https://github.com/mosop/optarg
https://github.com/mosop/cli
https://github.com/mrrooijen/commander
https://github.com/msa7/multi_auth
https://github.com/naqvis/snappy
https://github.com/naqvis/containerregistry.cr
https://github.com/naqvis/crystar
https://github.com/naqvis/cr-xmpp
https://github.com/nats-io/nats.cr
https://github.com/nbulaj/proxy-fetcher.cr
https://github.com/neovintage/accord
https://github.com/obsidian/oak
https://github.com/oz/pinboard.cr
https://github.com/philnash/crotp
https://github.com/philnash/envyable.cr
https://github.com/phoffer/inflector.cr
https://github.com/pine/crenv
https://github.com/rhysd/Crisp
https://github.com/robacarp/mosquito
https://github.com/rodrigopinto/can_use
https://github.com/rogeriozambon/http-protection
https://github.com/ruivieira/crystal-gsl
https://github.com/sam0x17/gcf.cr
https://github.com/schovi/baked_file_system
https://github.com/sdogruyol/tren
https://github.com/sdogruyol/cryload
https://github.com/sferik/twitter-crystal
https://github.com/spider-gazelle/rethinkdb-orm
https://github.com/splattael/hashids.cr
https://github.com/splattael/libnotify.cr
https://github.com/stumpycr/stumpy_png
https://github.com/szTheory/zaru_crystal
https://github.com/taylorfinnell/awscr-signer
https://github.com/tbrand/neph
https://github.com/topaz-crystal/topaz
https://github.com/unn4m3d/cppize
https://github.com/unn4m3d/crystaledge
https://github.com/veelenga/play-crystal.el
https://github.com/vjdhama/crystal-cookbook
https://github.com/vladfaust/time_format.cr
https://github.com/vnbrs/burocracia.cr
https://github.com/waterlink/mocks.cr
https://github.com/westonganger/form_builder.cr
https://github.com/z64/openssl.cr
https://github.com/ziprandom/cltk
https://github.com/ziprandom/graphql-crystal

https://gitlab.com/crystallabs/crystime
https://github.com/drhuffman12/ai4cr
https://github.com/epoch/tallboy
https://github.com/icyleaf/totem
https://github.com/icyleaf/halite
https://github.com/johnjansen/ternary_search_tree
https://github.com/jwaldrip/admiral.cr
https://github.com/kingsleyh/crystal-rethinkdb
https://github.com/manastech/webmock.cr

### CODE REVIEW

**Comment by axvm** [comment]
https://travis-ci.org/axvm/cake/builds/634285441

**Comment by hugopl** [comment]
Is there a way to trigger a build on some of these CIs only when a new crystal version is released? Because makes no sense re-build the very same thing using the very same compiler n-times.

**Comment by Blacksmoke16** [comment]
That's a good point.  Although it is not a requirement, ideally shards would be testing agains both latest and nightly CI; which would help catch issues before a release actually happens.

In reality, we were thinking of only running this like once a month? So probably not a big deal.

**Comment by hugopl** [comment]
monthly builds seems fine... according to Travis CI:

> If your API or cron triggered builds run on the same commit or branch over and over again, you will notice GitHub have a limit of 1000 status updates per commit,

This means that after 83 years without a new commit the project build status will be wrong. Hope Crystal still good till there.

**Comment by chris-huxtable** [comment]
I've added weekly builds for:

- https://github.com/chris-huxtable/syslog.cr
- https://github.com/chris-huxtable/atomic_write.cr
- https://github.com/chris-huxtable/config.cr
- https://github.com/chris-huxtable/front_matter.cr
- https://github.com/chris-huxtable/pledge.cr

**Comment by veelenga** [comment]
Thanks @Blacksmoke16. I will review it during this week.

**Comment by Blacksmoke16** [comment]
This will be handled via https://github.com/veelenga/awesome-crystal/pull/489 now.

**Pull request closed without merging**
