### PR TITLE
Adds syslog.cr

### PR DESCRIPTION
**Pull request by chris-huxtable**
I now notice that there is an existing shard. Mine differs in that it uses sys-calls which would insure platform independence.

### CODE REVIEW

**Comment by veelenga** [comment]
@comandeo @chris-huxtable what do you think about merging this into one shard?

**Comment by comandeo** [comment]
Hey! I am not sure whether we can merge these two somehow. We just need to pick one, I believe. 

I do not use my shard anymore, so it is kind of abandoned. If the one from @chris-huxtable is actively maintained and in use, I think we should go with it.

**Comment by veelenga** [comment]
@comandeo I don't see any reason to remove your shard from the list. It still works and compatible with the latest Crystal.

@chris-huxtable what do you think about the following:

1. Add specs
2. Follow the default formatting (`crystal tool format`)
3. Add CI
4. Rename the description to something like "Bindings for syslog"
4. Move it to [C Bindings](https://github.com/veelenga/awesome-crystal#c-bindings) section

Also, if it is going to be added to Crystal stdlib (https://github.com/crystal-lang/crystal/issues/6545), we should not merge it. /cc @RX14

**Comment by RX14** [comment]
It's not going to be added to the stdlib soon. And I already know what @chris-huxtable will say about using the standard formatter. The rest of the suggestions are fine.

**Comment by veelenga** [comment]
Looks awesome!

**Pull request merged**
