### PR TITLE
Add migrate

### PR DESCRIPTION
**Pull request by vladfaust**
[micrate.cr](https://github.com/juanedi/micrate) is abandoned - it has forever pending pull requests with needed features and never updated issues.

I've developed a simpler solution ([migrate](https://github.com/vladfaust/migrate.cr)), which resolves following issues:

- https://github.com/juanedi/micrate/issues/11
- https://github.com/juanedi/micrate/issues/13
- https://github.com/juanedi/micrate/issues/19
- https://github.com/juanedi/micrate/issues/20
- https://github.com/juanedi/micrate/issues/21

It may be possible to migrate from micrate to migrate :smile:: just add a table called `"version"` with a single `"version"` column with your latest migration version value. Also need to replace `-- +micrate Up/Down` with `-- !migrate up/down`, which is more universal.

Cheers.

### CODE REVIEW

**Comment by veelenga** [comment]
@vladfaust glad to see you here again 😄 
We have a new policy in [contribution guidelines](https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md) which does not allow us to add entries to the list which are younger than 30 days. Let's wait for the appropriate time.  

Should we remove micrate from the list or not? I vote no for now as it is used by amber and all apps running on amber. Sad it does not have the appropriate support @juanedi

**Comment by hugoabonizio** [comment]
@juanedi If you don't have time to maintain micrate anymore, I'm sure @crystal-community would be glad to take care of the issues. :smiley:

**Comment by vladfaust** [comment]
@veelenga that's alright, I can wait.

Regarded to Amber - I'll add a migration guide, which is simple as hell. Just need to replace one table by another.

Additionally, in my opinion, defining a non-universal word `+micrate` in plain `SQL` files is not practical. `!migrate` feels more native. And also not mentioned above, micrate eventually becomes buggy when doing lots of ups and downs and redos - that's because of complex version table, which `migrate` got rid of.

**Comment by veelenga** [comment]
👍 /cc @eliasjpr

**Comment by veelenga** [comment]
@vladfaust you didn't do any updates of your shard after submitting this PR.  Are you going to extend/maintain it? If not, it may not be that useful imho.

**Comment by vladfaust** [comment]
It is used in a couple of production projects and it serves well. All its issues are small enchansements. Let others say what they think, @veelenga, otherwise Crystal newcomers will see the only migrate solution which is abandoned 🤨

Will improve README today though.

**Comment by juanedi** [comment]
Hello everyone! I'm really sorry for disappearing 😅 

I never announced the project was dead because I always wished I could make time to work on it, but had a lot of things going on recently.

At this point I don't think I can put a lot of work into it for the moment, so these following days I'll try to make sure people know it's not actively maintained. Of course, if @crystal-community wants to take over it that's totally fine.

Thanks @vladfaust for bringing this up and providing an alternative! Maybe it just makes sense for people to start using that library.

Cheers!

**Comment by veelenga** [comment]
@juanedi you can move it to @crystal-community org of course, but the repo still needs to have a maintainer to continue growing... Some good projects became abounded being even a part of @crystal-community: https://github.com/crystal-community/amethyst. 

If you still want to move it, please let me know.

**Comment by eliasjpr** [comment]
@veelenga as this shard is used with Amber I would like to propose for the Amber team to maintain it. Let us know we would be happy to take it on.

**Comment by veelenga** [comment]
@eliasjpr oh, this sounds great! Unfortunately, I don't have admin access to the repo, so can't help for a moment. You have to get in touch with @juanedi and move it to the amber organization or just maintain a fork. The first way is preferable because it will keep issues/pull requests/starts etc.

**Comment by juanedi** [comment]
@eliasjpr sounds good to me! thank you so much for offering ❤️ 
I'll reach out to you so we can chat and coordinate.

**Comment by eliasjpr** [comment]
Heads up, 

The Amber Framework team has assume maintenance responsibilities for the Micrate crystal shard. As we want to support the crystal community we will maintain Micrate as a complete separate shard. We will monitor and address issues in order of community importance, Welcome people to contribute as well. 

@juanedi as the author of the shard we will listen closely and take good consideration to his suggestions. Thank you for the hard work @juanedi.

With no further due point your shards to **amberframework/micrate** to get latest updates.

```
dependencies:
  micrate:
    github: amberframework/micrate
```

In the next few weeks we will be addressing some of the open issues. Feel free to ask question on the Gitter channel https://gitter.im/amberframework/amber

**Pull request merged**
