### PR TITLE
Add crystal_api

### PR DESCRIPTION
**Pull request by akwiatkowski**

### CODE REVIEW

**Comment by veelenga** [comment]
@akwiatkowski thanks for contributing. You are positioning crystal_api as "Toolset for creating REST Api in Crystal Language", not sure if we have to add it to Web frameworks.

We can add a new section "Api builders" and put it there. What do you think ? Seems like it is enough general group for new records...

**Comment by akwiatkowski** [comment]
It's your call :)
I have put there because at that moment it was the best position, but if you wish I could change this pull request to.

**Comment by veelenga** [comment]
I asked you because you are the best person who understands the purpose of the project and thus a section it relates to. 

I prefer to have a new section described above. Please update and do git amend (or squash) ;-)

**Comment by akwiatkowski** [comment]
Done. Hope it looks good.

**Comment by veelenga** [comment]
Yup, it is good :+1: 
Thanks

**Pull request merged**
