### PR TITLE
Add ynab.cr to third-party APIs list

### PR DESCRIPTION
**Pull request by jaredsmithse**
Add [ynab.cr](https://github.com/jaredsmithse/ynab.cr), a wrapper for the YNAB API.

### CODE REVIEW

**Comment by vladfaust** [comment]
image
image
image
image

**Comment by veelenga** [comment]
@jaredsmithse please follow the [contribution guidelines](https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md).

Also:

- add usage instructions 
- add CI periodical builds

**Comment by veelenga** [comment]
@vladfaust thanks for pointing this out. I haven't checked the repo :)

**Comment by jaredsmithse** [comment]
@veelenga I added usage instructions and made another release that was not pre-release. I setup Travis to do daily builds as well! 

Thanks for the quick feedback 🙂

**Comment by djdarkbeat** [comment]
@jaredsmithse I use the last version of YNAB before the SASS version, I would like to contribute but this is only for the API for the SASS version, correct?

**Comment by jaredsmithse** [comment]
@djdarkbeat correct! I only started using about two years ago. I was aware they converted to SaaS but wasn't even aware of the other API 😅

**Pull request merged**
