### PR TITLE
adding graphql

### PR DESCRIPTION
**Pull request by jney**

### CODE REVIEW

**Comment by vladfaust** [comment]
According to https://github.com/rmosolgo/graphql-libgraphqlparser-ruby, where Ruby is ~4-9 times slower than C++; and https://github.com/ziprandom/graphql-crystal, where Crystal is ~50 times slower than C++, I can assume that @ziprandom's implementation may be too slow to be in Crystal **awesome** list (no offense)?

**Comment by veelenga** [comment]
This is the best implementation of graphql for Crystal that is currently available. If we would have a better alternative, we would be able to change it at any time. For now, let people choose whether it is bad or good for them. Anyway, @ziprandom may work and improve performance soon ;)

**Comment by jney** [comment]
done

**Comment by vladfaust** [comment]
@veelenga I started learning Crystal after being disappointed of how is Ruby's GraphQL slow (that moment there was no any Crystal GraphQL). And now there is a single one even slower than Ruby's. I hope the author implements the faster version ASAP. :racehorse: 

And yes, I'm not so smart to implement GraphQL myself.

**Comment by ziprandom** [comment]
Just a comment from the author of graphql. The calculations made to asses that grapqhl-crystal is slower than the ruby implementation are pretty inaccurate imho and I actually expect graphql-crystal to already be significantly faster than the ruby implementation in real world scenarios. 

I added a benchmark to compare the performance of the parser, and only the parser to libgraphqlparser. There i'm parsing a pretty big chunk of graphql definitions, which rarely occurs in the wild. 

What's missing at the moment is a real benchmark to asses the performance of the whole system, as other factors like validation come into play here. https://github.com/playlyfe/go-graphql/tree/master/benchmarks is a good starting point, and somone already seems to be working on that (or the new parser implementation): https://github.com/ziprandom/graphql-crystal/issues/1#issuecomment-325192637.

I was honest to post the results of my parser benchmark which was meant to be more of a test of the cltk toolkit that I used to create the parser and already led to improvements there. Seeing that this interpreted out of context and leading to such inaccurate conclusions is kind of sad and makes we wonder whether I should remove the mention of this benchmark altogether from the projects page.

**Pull request merged**
