### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by veelenga**
Unfortunately, we have to remove a variety of unmaintained, broken or unusable for now entries. If you have any arguments/suggestions regarding removal, please be free to add comments. I'm going to merge this in a couple of days.

refs #171

<details>
<summary>Here is a full list</summary>

https://github.com/BlaXpirit/crystal-dbus
https://github.com/DougEverly/daemonize.cr
https://github.com/MakeNowJust/crake
https://github.com/MakeNowJust/crystal-diff
https://github.com/Sija/serialport.cr
https://github.com/SuperPaintman/etag
https://github.com/TPei/observable
https://github.com/TyanNN/kemal-comments
https://github.com/adlerhsieh/lake
https://github.com/agatan/watchbird
https://github.com/akwiatkowski/ranger
https://github.com/aladagemre/chizge
https://github.com/askn/fikri
https://github.com/asterite/fast_sleep
https://github.com/azukiapp/crystal-chalk-box
https://github.com/bcardiff/crystal-routing
https://github.com/benoist/gelf-crystal
https://github.com/benoist/snappy-crystal
https://github.com/benoist/zeromq-crystal
https://github.com/chenkovsky/docopt.cr
https://github.com/chenkovsky/heap.cr
https://github.com/chenkovsky/nanomsg.cr
https://github.com/crystal-lang/crystal
https://github.com/datanoise/openssl.cr
https://github.com/david50407/csmli
https://github.com/davydovanton/AnyBar_cr
https://github.com/dkhofer/primes
https://github.com/f/lambda.cr
https://github.com/fg/gravatar.cr.git
https://github.com/fixcr/matchi
https://github.com/fridgerator/fantasy_football_nerd_api
https://github.com/generate-cr/generate
https://github.com/googya/pullword
https://github.com/greyblake/crystal-glosbe
https://github.com/greyblake/crystal-google_translate
https://github.com/greyblake/crystal-kiwi
https://github.com/jeromegn/bson.cr
https://github.com/jeromegn/docker.cr
https://github.com/johnjansen/text
https://github.com/jtomschroeder/crystalline
https://github.com/karupanerura/router-simple.cr
https://github.com/kofno/crystal_av
https://github.com/kostya/executable_path
https://github.com/krisleech/evented
https://github.com/kuende/kt
https://github.com/kyrylo/airbrake-crystal
https://github.com/lucasocon/openweather.cr
https://github.com/luislavena/beryl
https://github.com/manastech/crystal_brium
https://github.com/mosop/metaclass
https://github.com/pablotron/libmagic-crystal
https://github.com/pine/crystal-connpass
https://github.com/pine/crystal-qiita
https://github.com/pine/crystal-resque-client
https://github.com/porras/mock
https://github.com/puppetpies/crystal-libpcap
https://github.com/puppetpies/crystal-libtar
https://github.com/puppetpies/kemal-monetdb-test
https://github.com/raydf/smtp.cr
https://github.com/rhysd/crdoc
https://github.com/rosylilly/power_assert.cr
https://github.com/ruivieira/curses
https://github.com/samsheff/Bunny
https://github.com/sdogruyol/kemal-mysql
https://github.com/sdogruyol/kemal-pg-sample
https://github.com/sferik/soundcloud-crystal
https://github.com/sferik/twitter-crystal
https://github.com/spalladino/wit-crystal
https://github.com/timuckun/crystal-liblmdb
https://github.com/ucmsky/crystalforce
https://github.com/veelenga/shorturl.cr
https://github.com/veelenga/vicr.git
https://github.com/vjdhama/ambience
https://github.com/waj/crystal-newrelic
https://github.com/waterlink/crystal-mysql
https://twitter.com/shardscrystal
</details>

### CODE REVIEW

**Comment by luislavena** [comment]
I'm working with my company to open source the latest changes to luislavena/beryl, but it might take a bit more than a few days 😑

**Comment by veelenga** [comment]
@luislavena beryl is a nice project. Personally, I would love to see updates on it. I think we can leave it in a list as it is going to be maintained in the nearest future 🤔  😏

**Comment by imdrasil** [comment]
I understand that crystalline has no support for a long time but as I know for now it's te only scientific li b for now (looking for help to solve this 😊) so as for me we should leave it here for some time. Also bson is the only one binding for bson (may be wrong)

**Comment by veelenga** [comment]
@imdrasil I understand your point, but as for me, broken projects for a long time are almost useless. And more time they stay broken, harder to update them or reuse some code. Also:

* removing from the list does not mean the project not available anymore
* it can be added later again if it will start giving some profit

PS: I also liked bson project, so I created [PR](https://github.com/jeromegn/bson.cr/pull/1) to support the latest Crystal... Will see how it goes. To do the same with Crystalline is much harder to me, so many errors 😢

**Comment by konovod** [comment]
With Crystalline - i've tried to fix and fixed everything except graph traversing: https://github.com/konovod/crystalline
Not doing PR as traversing still don't compiles - there is some problem with generic types of BFS\DFS iterators, trying to solve it.

**Comment by veelenga** [comment]
@konovod Wow, nice job. Let me know if I need help with that

**Comment by konovod** [comment]
Well, i've got to point where compiler accepts traverse_spec.cr but crashes at codegen phase. Next step should be identifying minimal example and posting to crystal-lang as a bug (and possibly finding workaround). Maybe i'll try to do it in a week.
    Given how fragile generics inheritance is, i'm surprised that library with such heavy use of generics gets so far.

**Pull request merged**
