### PR TITLE
Add meet

### PR DESCRIPTION
**Pull request by jgarte**
## Link

https://github.com/ryanprior/meet

## Checklist
* [x] - Shard is at least 30 days old.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
@jgarte Could use a rebase on master. Pretty sure CI would fail due to it not being in ABC order.

**Comment by jgarte** [comment]
> @jgarte Could use a rebase on master. Pretty sure CI would fail due to it not being in ABC order.

@Blacksmoke16 Thanks for catching that! I re-pushed with the fix.

**Review by Blacksmoke16 — APPROVED** [review]
@veelenga Can you make the travis check no longer required in favor of the GH Action one?

Other than that, this looks good to me.

**Review by veelenga — APPROVED** [review]

**Comment by veelenga** [comment]
@Blacksmoke16 done.

**Pull request merged**
