### PR TITLE
add hash_ring

### PR DESCRIPTION
**Pull request by TobiasGSmollett**
I added hash_ring. It's an implementation of consistent hash that allow the fast dynamic assignment in distributed server environment.

### CODE REVIEW

**Comment by veelenga** [comment]
Happy to see it is now a part of Awesome Crystal list ❤️ 💎 

### What's next?

* announce it on [Crystal ANN](https://crystal-ann.com/) dev hub
* share it on [Reddit channel](https://www.reddit.com/r/crystal_programming/)
* say about it if you created something [the community is looking for](https://github.com/crystal-community/crystal-libraries-needed/issues)

**Comment by vladfaust** [comment]
I clearly don't get why this is *awesome*. Basically, the documentation is devastatingly unclear and there is a big bold plate **WIP** and there is so few lines of code. A too little effort put into this shard yet to be it placed in *awesome* list. The language will not look better for newcomers if there are tons of shitty small **gists** marked as *libraries*.

No offence, @TobiasGSmollett, I know you contribute to Crystal and have really awesome libs, but these tiny chunks of code could be found via crystalshards.xyz, there is no point in placing it here.

**Comment by creadone** [comment]
@vladfaust, you not right, it is also awesome for learn code.

**Comment by RX14** [comment]
@vladfaust While the piece of code is small, it is both useful and probably took quite a bit of time and domain knowledge to write and optimise. I agree somewhat that using this repository as a generic list of shards is wrong, and there should be some standards and cleanup (old unmaintained shards, new shards should be from a reputable maintainer or have existed for a while)

**Comment by veelenga** [comment]
Hey, guys. Thanks for lift this up again :)

Well, my plan was to do cleanup periodically, maybe half of a year or so. #172 was the first try. That is a manual action and takes time... But was interesting, because I and other guys did updates of   some outdated projects to stay on the list 🎉 

@vladfaust if you or someone else want to do such a cleanup again or have ideas how to better support the list, I'm open for discussion. 

btw, i'm looking for the contributor #223 to help with maintenance ;)

**Pull request merged**
