### PR TITLE
Add blurhash.cr

### PR DESCRIPTION
**Pull request by Sija**
## Link
https://github.com/Sija/blurhash.cr

## Checklist
* [x] - Shard is at least 30 days old.
* [x] - Shard has CI implemented.
* [x] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).

### CODE REVIEW

**Comment by Sija** [comment]
@Blacksmoke16 Why did you modify my description, without my knowledge nor consent? In addition quite wrongly I have to add, because the shard **is** 30 days old (https://github.com/Sija/blurhash.cr/commit/2db54e2072e81c2e852476e9972bc0a31c681294). I take it as a quite rude behaviour from your side.

**Comment by Blacksmoke16** [comment]
Oh, then I wonder whats up with github. 

image

Shows the `initial commit` was 17 hours ago.  Yet, when you click on the commit

image

It says it was on Feb 26?

**Comment by Sija** [comment]
@Blacksmoke16 I was talking about your behavior, not the GitHub, to which you seem to want to direct the attention atm.

**Comment by veelenga** [comment]
@Sija I think there is some lack of testing. Imho specs are required for `encode` method.

**Comment by Sija** [comment]
@veelenga Thanks for reminding, I've amended those.

**Pull request merged**
