### PR TITLE
Added DOCX lib reference

### PR DESCRIPTION
**Pull request by aristotelesbr2014**
## Checklist
* [X] - Shard is at least 30 days old.
* [X] - Shard has CI implemented.
* [X] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
@aristotelesbr2014 Can you setup a periodic build?

**Comment by Blacksmoke16** [comment]
I guess not.

**Comment by aristotelesbr2014** [comment]
Sorry for the delay in responding. A lot of work in that period. The library does not receive updates because it is still meeting demand. I've done it around here so that maybe I can help someone else. But no, it is not being involved. When there is a need to open a PR again

Until then I hope the library will help the community Thanks!

**Comment by Blacksmoke16** [comment]
@aristotelesbr2014 Can you setup a periodic build?

**Comment by veelenga** [comment]
@aristotelesbr2014 sorry, closing this for now because of the inactivity. Please be free to reopen or submit another request.

**Pull request closed without merging**
