### PR TITLE
Added Phreak

### PR DESCRIPTION
**Pull request by shinzlet**
I've been working on a little CLI builder for a while, finally got around to making it conform with your contributing guidelines. If there are any issues, please let me know.

Thanks for maintaining this useful list!

### CODE REVIEW

**Comment by shinzlet** [comment]
Alright, I'll beef those up when I get a chance and get back to you soon. Thanks!

**Comment by RX14** [comment]
This is amazing, and pretty much what I believe should be in the standard library. It's well-documented, it doesn't use macros, and the code is simple and concise. I would love it if you made an issue on the crystal repo about reworking the `OptionParser` API, and included this shard as an API and code example. I'd support you through this.

In terms of this shard - we tend not to use tabs in crystal, instead using two spaces (`crystal tool format` enforces this). There's some bad indenting in your source files, especially the readme as it's rendered on github. This should be fixed.

**Comment by shinzlet** [comment]
@RX14
Thank you so much! I'm totally open to that idea, although there are a few things I'd like to get working before I pitched it. Currently, Phreak cannot generate a help menu, and I think that's important thing to cinch up!

Regarding the indentation issues, I wasn't aware that spaces were the convention - thanks for bringing that to my attention. I'll fix that, along with writing some more integration tests and then this PR should be ready to merge.

**Comment by shinzlet** [comment]
Alright, @veelenga, I've got a healthy collection of specs written and an irksome few bugs fixed. Also fixed the formatting issues that RX14 so helpfully pointed out. I'd love it if this PR could be accepted! Happy to address any other issues you might have with Phreak.

**Comment by veelenga** [comment]
Looks great. Thank you.

**Pull request merged**
