### PR TITLE
Added crystal cookbook

### PR DESCRIPTION
**Pull request by vjdhama**

### CODE REVIEW

**Comment by veelenga** [comment]
I think it will be a bit better to add this to [Tools](https://github.com/veelenga/awesome-crystal#tools) section, like I wrote in #39. 

I expect it to be:

* ...
* Resources
* Services and Apps
* Tools
  * DevOps &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;**<-- new subsection**
  * Editor Plugins

Please update and do git amend (or squash).

**Comment by vjdhama** [comment]
@veelenga Alright. I'll do the changes.

**Comment by vjdhama** [comment]
@veelenga Just updated the PR.

**Comment by veelenga** [comment]
Awesome, thanks :+1:

**Pull request merged**
